<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="8.15.0" />
    <PackageReference Include="Cerebellum.AuthBlocks.Web" Version="10.3.33" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeepDrftModels\DeepDrftModels.csproj" />
    <ProjectReference Include="..\DeepDrftShared.Client\DeepDrftShared.Client.csproj" />
  </ItemGroup>

</Project>
