<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Remove="browser" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="8.15.0" />
    <PackageReference Include="Cerebellum.AuthBlocks.Web" Version="10.3.32" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeepDrftModels\DeepDrftModels.csproj" />
    <ProjectReference Include="..\DeepDrftData\DeepDrftData.csproj" />
  </ItemGroup>

</Project>
